### PR TITLE
legal notice on header

### PR DESCRIPTION
**Pull request by jorjo1**
https://github.com/Rostlab/JS16_ProjectF/issues/482

### CODE REVIEW

**Comment by sacdallago** [comment]
Screenshot please?

**Comment by jorjo1** [comment]
image

**Comment by gyachdav** [comment]
smaller font and within 0.5 opacity div

**Comment by jorjo1** [comment]
image

**Comment by jorjo1** [comment]
So now we have a gridded content on the page, but the header looks a lot better now - full width. Forget about this floating nowhere elements now :dancer:

**Comment by sacdallago** [comment]
Something like:
header

?

**Comment by sacdallago** [comment]
You are also very welcome to just take that image and substitute it in the right location :D

**Comment by jorjo1** [comment]
If I take your image, @sacdallago , we are again in trouble because we don't see the whole image - smaller screens see that different from bigger screens. So why not leave this as a text? You mean I have to make it with our Cinzel font?

**Comment by sacdallago** [comment]
Definitely use the approach that you most like! I was just pointing out on the "style". I wouldn't have the text with a background grayish color, because: who cares! As long as there is the intention that we have it, and the text is selectable, it's good enough :)

**Edit** also, fontwise: whatever you like! :)

**Comment by sacdallago** [comment]
? anything here? :)

**Comment by yashha** [comment]
image
Edit:
image
It seems like the navbar is still messed up

**Comment by yashha** [comment]
I think this can be merged

**Comment by sacdallago** [comment]
@yashha weren't you talking about the nav-bar being messed up?

Same story as earlier, I would prefer develop to be merged into this branch and then to have a new PR to see that nothing is breaking.

Please open a new PR once develop --> header-legal

**Comment by yashha** [comment]
still messed up
It will be fixed with #475
because I shrinked the fontsize of the header there.

**Comment by yashha** [comment]
changes of this pr still working
image

**Pull request merged**
