### PR TITLE
Fixed map update config

### PR DESCRIPTION
**Pull request by yashha**
update:
https://github.com/Rostlab/JS16_ProjectC_Group10/commit/07eb25d3b70b16db03faaa0310bd7a2ddfb293ac

Needs tooltip and Flag button needs design adjustments.

### CODE REVIEW

**Comment by mammuth** [comment]
Same here:
I'm busy all day long and without my personal laptop. 

I can review your changes in the evening. If you want to see this merged sooner, someone else should do it :wink:

**Comment by sacdallago** [comment]
@mina-zaki please look at this PR, if the code and functionality are as expected: merge.

Thx

**Comment by mina-kleid** [comment]
Map now is working on that branch and i see paths and can use timeline, on contrary to develop where its broken

**Comment by sacdallago** [comment]
**C10** should have fixed the issue with the last version of their package

**Pull request merged**
