### PR TITLE
Changed more info link in map component

### PR DESCRIPTION
**Pull request by yashha**
#80

### CODE REVIEW

**Comment by gyachdav** [comment]
anyone knows how often the new commits get pulled into heroku?

**Comment by yashha** [comment]
Normally when there is something brilliantly new or we want to see of a new feature is working on the server.
From now on every pull is tagged

**Comment by gyachdav** [comment]
can we pull so I will see the map working? pretty please? I waited two days...

**Comment by yashha** [comment]
I pulled today already, but sure, if you want to see the more info tweak.

**Comment by mammuth** [comment]
@gyachdav As stated in the Readme of the repo the hook is set for the "staging" branch. 
So to deploy on heroku just pull from develop into staging.

**Pull request merged**
