### PR TITLE
Worked on startpage

### PR DESCRIPTION
**Pull request by yashha**
Desktop:
image

image

iPhone 5:
image

image

### CODE REVIEW

**Comment by mammuth** [comment]
Nice, I like how the Twitter graphs are on different rows on mobile 👍

**Comment by mammuth** [comment]
screen shot 2016-04-22 at 21 19 55

The tombstone is flying around. Should be aligned at the righter bottom again.

**Comment by yashha** [comment]
I think I did this because of smaller displays.
I can only make the tombstone align at the bottom when the copyright is not being overlapped.

**Comment by mammuth** [comment]
Then align it more on bottom (2-3px above it) and in a media query set it to your 12px for smartphones

**Comment by yashha** [comment]
image

**Comment by yashha** [comment]
@mammuth you are allowed to change it ;)

**Pull request merged**
