### PR TITLE
Added statistics from guy to statistics page

### PR DESCRIPTION
**Pull request by yashha**

### CODE REVIEW

**Comment by yashha** [comment]
Whats the problem? It works locally :(

Edit: It seems no raw-loader is being installed

**Comment by gyachdav** [comment]
please merge :clock1:

**Comment by gyachdav** [comment]
well i meant the other guys should merge... but okay :smile:

**Comment by yashha** [comment]
They are not around .. ^^

**Comment by yashha** [comment]
You can test it in 4 min on heroku :)

**Pull request merged**
