### PR TITLE
Made a component of the episode recap page and added to navigation

### PR DESCRIPTION
**Pull request by yashha**
I should probably highlight the disclaimer
image
image
image

### CODE REVIEW

**Comment by yashha** [comment]
image

**Comment by gyachdav** [comment]
Thanks for the quick turnaround @yashha. you take care of the CI errors?

**Comment by yashha** [comment]
There was a problem with the travis caches.
Now it works

**Comment by gyachdav** [comment]
Cool thanks @yasha.

@sacdallago please deploy.

**Comment by yashha** [comment]
We still have to make a link from the start page to it? don't we?

**Comment by sacdallago** [comment]
:D There's little to deploy :D this is not on develop

**Pull request merged**
