### PR TITLE
Hopefully fix for #272

### PR DESCRIPTION
**Pull request by TheZoker**

### CODE REVIEW

**Comment by jorjo1** [comment]
What is this branch for and who has to merge it in? Assign somebody ^^

**Comment by TheZoker** [comment]
@jorjo1 Its @sacdallago who has to review the change and test it on his system
And it's for fixing #272

**Comment by sacdallago** [comment]
I'll have a look later today.

**Comment by sacdallago** [comment]
Not working..If I look at the PR the only thing that changed is the config.json.template
You should be looking at the calls to the API, there should be a parameter specifying the port.. In the original issue I wrote you can see the commit in which the Twitter sentiment analysis group solved this problem.
They only had one call to the API, you might need to change this at every occurrence of an http/s call

**Comment by sacdallago** [comment]
apart from the build failing: what if the port is not defined?

**Comment by TheZoker** [comment]
I guess thats handled with the `try` here: https://github.com/Rostlab/JS16_ProjectF/blob/port-fix/configWebpack/common.js#L11

**Comment by sacdallago** [comment]
I'm meaning more in your constructed string for the request. You'd have an extra `:` there, not to talk about the possibility of having an `undefined` after that.
A simple `if` clause should solve your problem.

And please fix the build

**Comment by sacdallago** [comment]
Ok.

Let's wait for the rest of the group to answer my question on the issue to see if we need any more work on this

**Pull request merged**
