### PR TITLE
Added 404 fallback page

### PR DESCRIPTION
**Pull request by jorjo1**
Refers to #41 
:trollface:

### CODE REVIEW

**Comment by yashha** [comment]
@jorjo1 It seems like navbar isn't transparent anymore #63

**Comment by sacdallago** [comment]
Your cloud 3 looks suspiciously similar to the cloud3 I put on the http://got.show page :D 

P.S.: it was the second? Third? Google images hit ahahah

**Comment by jorjo1** [comment]
@sacdallago Yea I know I did this for a testing purpose, of course I created some of my own (and they are in the folder as well) but I lost track which was which. This is why I still have not merged them. Gonna fix them now :+1:

**Comment by sacdallago** [comment]
ahaha com'on, I'm not gonna sue you (or: will I?)

**Pull request closed without merging**
