### PR TITLE
Readded SentimentsApi + added 	Twitter top 5 loved and 	Twitter top 5 hated

### PR DESCRIPTION
**Pull request by yashha**
Design needed :)

### CODE REVIEW

**Comment by mammuth** [comment]
"Design needed" -> #298

**Comment by mammuth** [comment]
screen shot 2016-04-08 at 20 50 21

You might add Links to the character-detail pages. Just take a look at how I did it at the other ranking-fields.

**Comment by yashha** [comment]
> Design needed :)
> :smile:

**Comment by mammuth** [comment]
Part of #40

**Pull request merged**
