### PR TITLE
Fix link on Jon Snow Landing page

### LINKED ISSUE #405: wrong link
in 

https://got.show/jon-snow-is-not-dead.html

the link from Read more about our awesome Life & Death Predictions here!

Should go to: 

machine-learning-algorithm-predicts-death-game-of-thrones

but instead goes to 

https://got.show/ranking

### PR DESCRIPTION
**Pull request by mammuth**
Closes #405

### CODE REVIEW

**Comment by yashha** [comment]
We don't have to keep the md files for the landingpages

**Comment by sacdallago** [comment]
Oh no, no, no. I see where this is going.
Trust me when I say it is for your own good:
Tomorrow we bump to version 1.1 after one and only one PR, in which all of this landing pages stuff is taken care off!

It makes you feel that this is over (for now) :D :D

So. **one** PR, tomorrow, that fixes all landing page stuff. #403 #404 and the landing pages that @gyachdav is finalizing and will deliver tomorrow... ok?

**Comment by mammuth** [comment]
@yashha decide what you wanna do with this quick-fix :wink: 
(that I didn't directly push to develop :relaxed: )

**Comment by sacdallago** [comment]
I appreciate @mammuth :) I'll leave this open so that you guys can fix #403, #404 and the stuff that's gonna come tomorrow from @gyachdav  in this PR

I want you to have a mental stop :D I know: fix = PR, but let's make this one a little bit bigger and a little bit against the rules

**Comment by gyachdav** [comment]
Heed the wisdom of your project manager and take a break. If you get bored, there's a [new website](http://got.show) you might wanna check out. Tomorrow is a new day with a whole lot of new (now post release) issues.

**Comment by jorjo1** [comment]
Is the background for the graphs only for me transparent? https://got.show/statistics

**Comment by sacdallago** [comment]
That's apparently design @jorjo1

**Comment by sacdallago** [comment]
So how are we doing here?
@gyachdav has been illegally pushing to develop but we have already spread blood :skull: :laughing:

**Comment by yashha** [comment]
Wait one pr ...? :O

**Comment by sacdallago** [comment]
ARGH, can someone fix the conflicts please? I'll be up still 15 min, would like to merge, pull and deploy

**Comment by goldbergtatyana** [comment]
doing it now

**Pull request merged**
