### PR TITLE
Added tum bar at top

### PR DESCRIPTION
**Pull request by yashha**
image

### CODE REVIEW

**Comment by mammuth** [comment]
You might want to put some padding left of the technische Universität München and around the tum logo.

**Comment by yashha** [comment]
What about putting it ontop of the image/nav?

**Comment by yashha** [comment]
image

on hover: 
image

**Comment by mammuth** [comment]
I'd prefer the grey version. Because it looks like the bar is not part of the actual page...

**Comment by yashha** [comment]
like this?
image

**Comment by mammuth** [comment]
Like your first version
0e1b4578-08ce-11e6-8c20-5fe2cfd422d0
This ugly bar is no part of the website. In this version it's visually no part as well.

**Comment by yashha** [comment]
I don't like that it is that white.
I would like the second approach.
What does the other guys say?
@jorjo1 @gyachdav @sacdallago

**Comment by gyachdav** [comment]
I'd go for this 

image

Without the hover (the hover is not a requirement is it?) 

This is the least obtrusive version

Have some margins/padding around the text so it wont be stuck to the borders like it is now.

**Comment by yashha** [comment]
image

**Comment by gyachdav** [comment]
@yashha can you move the text closed to the left border and the logo to the right border?

**Comment by yashha** [comment]
Its possible I think, but not easy.

**Comment by mammuth** [comment]
Why not just make it as it was before and add a padding left/right?

**Comment by yashha** [comment]
I think it doesn't look that good too.

image

Maybe it looks better with fullsize background image

**Comment by jorjo1** [comment]
@yashha I fixed the image, it has now full size, just merge my branch..

**Comment by sacdallago** [comment]
Guys. Guys. Slow down! As I told you there are specific rules on colors, position and other things!

Please:
- No hover,
- try to use the same font as on the tum webpage (I think they have a PNG also for the FQDN 😂  Techinsche Universität München ),
- make the whole thing a thick bigger (otherwise it looks like a mistake we forgot there),
- there should be padding above and under the tum logo and tum name, same as in comment https://github.com/Rostlab/JS16_ProjectF/issues/482#issuecomment-213373338 (try to stick to that color scheme (which should fit the got.show style) and general formatting **as much as possible**)

I suggest you to not have the logo right:0 and the FDQN left:0, but to have a div of the same size of the page container (ie. width == to header width, 550 on my screen but it surely depends on screen size) and then inside this centered div have the two logos on right:0 and left:0

I hate to be the one making you do this, but implementing it to then have the legal office complain about it again is also not gonna bring us any further!

Again: Thank you sooooo much for doing this!

**EDIT**: Here you have the color-scheme and some other hints: https://portal.mytum.de/pressestelle/tum_mit/2007nr2/09.pdf

**Pull request closed without merging**
