### PR TITLE
Fixed switching from statistics and back and removed donut

### LINKED ISSUE #426: Doughnut to simple numbers
Please change the doughnut in the characters page to:

> Overall, we register some **XX positive tweets** and **YY negative tweets** for character ZZZ.

Where the positive tweets and negative tweets have the color of the positive/negative smily faces above, in the graph :)

### PR DESCRIPTION
**Pull request by yashha**
Closes #426, #416

### CODE REVIEW

**Comment by yashha** [comment]
no review?

**Comment by sacdallago** [comment]
it's broken

**Comment by sacdallago** [comment]
screen shot 2016-04-16 at 1 43 01 am

**Comment by sacdallago** [comment]
I reopened the branch and reverted the PR. Please fix the error and open a new PR @yashha

**Comment by yashha** [comment]
Thats strange:
image

**Comment by sacdallago** [comment]
My thesis is confirmed! The other PR broke this one!

What's gonna happen now:
1. I will undo the changes of #449 
2. Please fix whatever causes the problem for the tweets to be always set to 0
3. You shall open a new PR for this branch, which will be merged and is approved right away

For now I'm running the checkout of commit: 3e1856fd98e131032eb2c7fa976959b38f56b841
that came before the PR merge of #449 

[and this seems to be working](https://got.show/characters/Joffrey%20Baratheon)

Good job btw! :D Needless to say that the problem could just arise by having the code of both PRs.. and who would have thought....

**Pull request merged**
