### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by TheZoker**

### CODE REVIEW

**Comment by jorjo1** [comment]
Please give more details in the commits :D

**Comment by yashha** [comment]
Should I squash this ^^
So many commits for 3 lines of changes?

**Comment by jorjo1** [comment]
Did it fix something?

**Comment by yashha** [comment]
No its only resorting our dependencies in devdeps and deps and updating some packages like bable-core

**Comment by jorjo1** [comment]
That's my observation too. So we delete? :)

**Comment by sacdallago** [comment]
Let @TheZoker tell us more about this

**Comment by TheZoker** [comment]
I'm sorry for the late response. 
It's not really a fix, but the expected speciation of dependencies and devDependencies. Because the modules in devDependencies are only used for dev environment, they should be inside the devDependencies and not dependencies. That's what the "fix" is about

**Comment by sacdallago** [comment]
@TheZoker you latest commit seemed to break the build process and I don't know if merging something like this makes sense at this stage... I trust you, if you tell me that this:
1. Won't break anything, and
2. Is necessary

then please re-open the PR

**Comment by TheZoker** [comment]
@sacdallago What build does not work?
On travis everything is fine: https://travis-ci.org/Rostlab/JS16_ProjectF/builds/121840540

All commits where test commits, the only change all-in-all is the [movement of 3 packages](https://github.com/Rostlab/JS16_ProjectF/pull/344/files) into the devDependencies, so there should not be a huge issue,

But it's definitely not necessary to move them! Its just they way, we should do it,

**Pull request closed without merging**
