### PR TITLE
added campaign line to header

### PR DESCRIPTION
**Pull request by jorjo1**
image

### CODE REVIEW

**Comment by goldbergtatyana** [comment]
YES from me as well!
To the sentence on the banner I would add "Help us get to the Morpheus Cup and win in Luxembourg".
Beautiful design btw!

**Comment by jorjo1** [comment]
Ok I will add "win"! 

Somehow my fingers slipped and mistyped it :D

@sacdallago

**Comment by mammuth** [comment]
Pretty!

**Comment by gyachdav** [comment]
@sacdallago ooooooooooo!!!!!!!!!!!!

**Comment by sacdallago** [comment]
Code looks good. Thing looks good. Merging and deploying

**Comment by sacdallago** [comment]
Hey @jorjo1 I noticed some misalignment of the _donate_ button on mobile. Can this be looked at? :)

**Comment by gyachdav** [comment]
Also please chase the text to

Help us go to LUXEMBOURG and win the MORPHEUS CUP.!

Should also be changed in the FB page.

**Pull request merged**
