### PR TITLE
Statistics on home

### PR DESCRIPTION
**Pull request by jorjo1**

### CODE REVIEW

**Comment by yashha** [comment]
Maybe make the image a bit smaller, and the website is not called a song of ice and data, isn't it? :)

**Comment by jorjo1** [comment]
"the website is not called a song of ice and data" what is the reference?

**Comment by yashha** [comment]
sry it is called song of ice and data :)
https://beta.got.show/ <-  title

**Comment by jorjo1** [comment]
i will do the image smaller ^^ #388

**Pull request merged**
