### PR TITLE
Added Contribution, credits and about with dropdown and statistics to the navbar

### PR DESCRIPTION
**Pull request by yashha**
screenshot from 2016-04-02 16 32 43

@gyachdav 
Is this ok, or do you want the links in the footer?

### CODE REVIEW

**Comment by gyachdav** [comment]
1. What does the About heading looks like when it is not clicked? 
2. What does it look like when its not hovered? 
3. Does the down arrow present all the time or only when the tab is active?

**Comment by gyachdav** [comment]
No Home tab in heading. we already linked the logo to home

**Comment by yashha** [comment]
screenshot from 2016-04-02 20 09 36

**Comment by sacdallago** [comment]
I, in general, don't like nested menus.
I see the point in having it here, but I can't say I like it.
In this case, I'd rather resort into making one page and having three sections.

It's my personal feelings... So, whatever.

**Comment by gyachdav** [comment]
Agreed. Let's not have nested menus in the navbar. Instead let's have an About tab that will send us to the About page described in https://github.com/Rostlab/JS16_ProjectF/issues/234

**Comment by gyachdav** [comment]
Also:
- [x] Remove Home tab 
- [x] Character -> Character**s**

**Comment by sacdallago** [comment]
About the Character > CharacterS you open an old wound @gyachdav :D didn't I also mention this in accordance to the link? /characterS

**Comment by yashha** [comment]
Shell I add now a contribute tab as you said in #227? @gyachdav

**Comment by gyachdav** [comment]
thanks for noticing this inconsistency.  I updated the Navbar issue https://github.com/Rostlab/JS16_ProjectF/issues/227#issue-145298270  

Yes let's see what it looks like having 6 tabs in the navbar.

**Pull request merged**
