### PR TITLE
uploaded table to recaps

### PR DESCRIPTION
**Pull request by jorjo1**
#525

image

### CODE REVIEW

**Comment by jorjo1** [comment]
I've no idea why, at this moment, the thing is not building.. :sleeping: I'll take a look tomorrow.

**Comment by sacdallago** [comment]
Maybe this will help:

```
build modulesModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' ../../../../config/markdown/table-recap.md in /home/travis/build/Rostlab/JS16_ProjectF/app/components/public/EpisodesRecap
```

**Comment by yashha** [comment]
Well there is no file called `/config/markdown/table-recap.md`

**Comment by jorjo1** [comment]
Oh sheets, I have forgotten to add the file :x: 
Forgive me please.

@sacdallago you can now upload it :+1:

**Pull request merged**
