### PR TITLE
Fixed issue that charts has been loaded twice

### LINKED ISSUE #369: Twitter sentiment graph buggy?
I saw that this happens only on the website provided by you, not on csv.got.show. Basically:

When I open up the page I get the graph with a certain zoom, thus some labels on top of the graph like "season XYZ". If then I zoom around, the original labels stay and some more labels are produced that move according to zoom or navigation (Screenshot attached, notice that "season 05" between season 03 and season 04)

screen shot 2016-04-10 at 3 06 47 pm

It happens both on the character page as well as on the homepage, you might want to look at the https://beta.got.show (now with consistent, curated tweets and sentiment analysis)

### PR DESCRIPTION
**Pull request by yashha**
Problem was that on every vDOM change an chart has been added
Fixes #369

### CODE REVIEW

**Comment by sacdallago** [comment]
Have you tested this?

**Comment by sacdallago** [comment]
I mean, as far as chrome/firefox go?

**Comment by yashha** [comment]
Chrome worked fine
How I can reopen the pr?

**Comment by sacdallago** [comment]
I created a new one! Sorry for that :D

**Pull request merged**
