### PR TITLE
Build

### PR DESCRIPTION
**Pull request by yashha**
Got travis, build and dev server working
Removed public/build folder
#26

I fixed the css issue at build, in this pull request, by using bootstrap instead of bootstrap-webpack

### CODE REVIEW

**Comment by mammuth** [comment]
Cool. What is the build procedure now /what happens?

**Comment by yashha** [comment]
css: will get linted and autoprefixed and extracted in style.css
jsx/js: will be compiled with babel and bundled in bundle.js

jquery will be imported as $, jQuery and window.jQuery

`new webpack.optimize.CommonsChunkPlugin('vendors', 'vendors.js')` can be removed, since we don't need to use the common code feature.

Minimization: OccurenceOrderPlugin and UglifyJsPlugin

**Comment by mammuth** [comment]
The deploy to Heroku happens when we merge into the build-branch, right?

**Comment by yashha** [comment]
yes

**Comment by yashha** [comment]
I start merging now

**Pull request merged**
