### PR TITLE
Sentimentsgraph resize now working

### LINKED ISSUE #445: Only one Twitter Graph on Homepage gets resized
Only the right graph gets resized, the left one is simply overshadowed. 

The function `d3.select(window).on('resize', function(){ . . . });` has to resize both charts

Extreme example:
resize error

### PR DESCRIPTION
**Pull request by yashha**
Closes #445

### CODE REVIEW

**Comment by sacdallago** [comment]
Find it strange that we went from `object.function()` notation to `function()( object.function() )` notation. But I guess this has been tested. If @jorjo1 agrees, merge :)

**Comment by yashha** [comment]
we went from `object.function` to `function(){object.function()}`  
and object.function is also a function

**Comment by yashha** [comment]
Here we should add the Feature of #459

**Comment by jorjo1** [comment]
You could've done it also with columns from bootstrap, but that's another beautiful way. 10/10

**Pull request merged**
