### PR TITLE
ranking title block

### PR DESCRIPTION
**Pull request by jorjo1**

### CODE REVIEW

**Comment by yashha** [comment]
What about making the image the a higher width than the "Who is most likely to die next" container, so it contains it?

**Comment by jorjo1** [comment]
It was the main idea to make it pop out :D

**Comment by jorjo1** [comment]
oh something got wrong..

**Comment by mammuth** [comment]
What's the current status on this, @jorjo1? 

For readers: It currently looks like this:
screen shot 2016-04-11 at 21 18 13

**Pull request merged**
