### PR TITLE
made the tum bar smaller

### PR DESCRIPTION
**Pull request by yashha**

### CODE REVIEW

**Comment by gyachdav** [comment]
Screenshots please in case they're different from what you previously sent.

**Comment by yashha** [comment]
image

image

**Comment by sacdallago** [comment]
Ohhhh this is what you have worked on. OK! I will pull this code once there's a little less traffic, the server is busy as it is

**Comment by yashha** [comment]
It's already pulled

**Comment by sacdallago** [comment]
Oh shit. ahaha sorry, I'm just overloaded

**Pull request merged**
