### PR TITLE
npm v2.14.20 and node v4.4.1

### PR DESCRIPTION
**Pull request by cotsog**
Fixes html-webpack-plugin problem.

### CODE REVIEW

**Comment by sacdallago** [comment]
Hi @cotsog thanks for contributing.

Your changes break travis:

``` bash
Setting up build cache
$ export CASHER_DIR=$HOME/.casher
0.05s$ Installing caching utilities
0.00s
0.63sattempting to download cache archive
fetching PR.271/cache--node-4.4.1.tgz
fetching PR.271/cache--node-4.4.1.tbz
fetching fix-build/cache--node-4.4.1.tgz
fetching fix-build/cache--node-4.4.1.tbz
fetching master/cache--node-4.4.1.tgz
fetching master/cache--node-4.4.1.tbz
could not download cache
0.00s
0.26sadding /home/travis/build/Rostlab/JS16_ProjectF/node_modules to cache
Starting with io.js 3 and Node.js 4, building native extensions requires C++11-compatible compiler, which seems unavailable on this VM. Please read https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.
$ node --version
v4.4.1
$ npm --version
2.14.20
$ nvm --version
0.31.0
before_install
6.54s$ npm install -g npm@2.14.20
/home/travis/.nvm/versions/node/v4.4.1/bin/npm -> /home/travis/.nvm/versions/node/v4.4.1/lib/node_modules/npm/bin/npm-cli.js
npm@2.14.20 /home/travis/.nvm/versions/node/v4.4.1/lib/node_modules/npm
install
23.87s$ npm install 
npm WARN peerDependencies The peer dependency webpack@1 || ^2.1.0-beta included from webpack-dev-middleware will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@1.0.11
ga-react-router@2.0.0 node_modules/ga-react-router
thenby@1.1.3 node_modules/thenby
object-assign@4.0.1 node_modules/object-assign
react-router-bootstrap@0.20.1 node_modules/react-router-bootstrap
react-dom@0.14.8 node_modules/react-dom
es6-promise@3.1.2 node_modules/es6-promise
webpack-hot-middleware@2.10.0 node_modules/webpack-hot-middleware
├── html-entities@1.2.0
├── querystring@0.2.0
├── ansi-html@0.0.5
└── strip-ansi@3.0.1 (ansi-regex@2.0.0)
compression@1.6.1 node_modules/compression
├── on-headers@1.0.1
├── bytes@2.2.0
├── vary@1.1.0
├── compressible@2.0.7 (mime-db@1.22.0)
├── debug@2.2.0 (ms@0.7.1)
└── accepts@1.3.2 (negotiator@0.6.0, mime-types@2.1.10)
express@4.13.4 node_modules/express
├── range-parser@1.0.3
├── escape-html@1.0.3
├── array-flatten@1.1.1
├── utils-merge@1.0.0
├── vary@1.0.1
├── merge-descriptors@1.0.1
├── cookie-signature@1.0.6
├── methods@1.1.2
├── content-type@1.0.1
├── fresh@0.3.0
├── content-disposition@0.5.1
├── cookie@0.1.5
├── parseurl@1.3.1
├── path-to-regexp@0.1.7
├── etag@1.7.0
├── serve-static@1.10.2
├── depd@1.1.0
├── qs@4.0.0
├── debug@2.2.0 (ms@0.7.1)
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.4.1 (unpipe@1.0.0)
├── proxy-addr@1.0.10 (forwarded@0.1.0, ipaddr.js@1.0.5)
├── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.10)
├── type-is@1.6.12 (media-typer@0.3.0, mime-types@2.1.10)
└── send@0.13.1 (destroy@1.0.4, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
superagent@1.8.3 node_modules/superagent
├── methods@1.1.2
├── component-emitter@1.2.0
├── cookiejar@2.0.6
├── reduce-component@1.0.1
├── extend@3.0.0
├── mime@1.3.4
├── formidable@1.0.17
├── qs@2.3.3
├── debug@2.2.0 (ms@0.7.1)
├── readable-stream@1.0.27-1 (inherits@2.0.1, string_decoder@0.10.31, isarray@0.0.1, core-util-is@1.0.2)
└── form-data@1.0.0-rc3 (async@1.5.2, combined-stream@1.0.5, mime-types@2.1.10)
bootstrap@3.3.6 node_modules/bootstrap
jquery@2.2.2 node_modules/jquery
history@2.0.1 node_modules/history
├── deep-equal@1.0.1
├── query-string@3.0.3 (strict-uri-encode@1.1.0)
├── warning@2.1.0 (loose-envify@1.1.0)
└── invariant@2.2.1 (loose-envify@1.1.0)
request@2.69.0 node_modules/request
├── aws-sign2@0.6.0
├── forever-agent@0.6.1
├── tunnel-agent@0.4.2
├── oauth-sign@0.8.1
├── is-typedarray@1.0.0
├── caseless@0.11.0
├── stringstream@0.0.5
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── extend@3.0.0
├── tough-cookie@2.2.2
├── node-uuid@1.4.7
├── qs@6.0.2
├── mime-types@2.1.10 (mime-db@1.22.0)
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── form-data@1.0.0-rc4 (async@1.5.2)
├── aws4@1.3.2 (lru-cache@4.0.1)
├── bl@1.0.3 (readable-stream@2.0.6)
├── hawk@3.1.3 (cryptiles@2.0.5, boom@2.10.1, sntp@1.0.9, hoek@2.16.3)
├── http-signature@1.1.1 (assert-plus@0.2.0, jsprim@1.2.2, sshpk@1.7.4)
└── har-validator@2.0.6 (pinkie-promise@2.0.0, commander@2.9.0, chalk@1.1.3, is-my-json-valid@2.13.1)
react-router@2.0.1 node_modules/react-router
├── invariant@2.2.1 (loose-envify@1.1.0)
└── warning@2.1.0 (loose-envify@1.1.0)
gotsentimental@0.4.1 node_modules/gotsentimental
├── agentkeepalive@2.1.0
├── polarity@0.2.0 (afinn-111@0.1.5)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── twit@2.2.3 (mime@1.3.4, bluebird@3.3.4, request@2.58.0)
└── mongoose@4.4.11 (sliced@1.0.1, ms@0.7.1, hooks-fixed@1.1.0, regexp-clone@0.0.1, async@1.5.2, muri@1.1.0, mpromise@0.5.5, kareem@1.0.1, mpath@0.2.1, bson@0.4.22, mquery@1.10.0, mongodb@2.1.14)
gotdailysentiment@0.0.7 node_modules/gotdailysentiment
├── twitter@1.2.5 (deep-extend@0.3.3)
├── util@0.10.3 (inherits@2.0.1)
├── sentiment@1.0.6 (lodash.assign@4.0.1)
└── mongoose@4.4.11 (ms@0.7.1, sliced@1.0.1, regexp-clone@0.0.1, hooks-fixed@1.1.0, async@1.5.2, muri@1.1.0, mpromise@0.5.5, kareem@1.0.1, mpath@0.2.1, bson@0.4.22, mquery@1.10.0, mongodb@2.1.14)
gotmap@0.1.3 node_modules/gotmap
└── leaflet@0.7.7
jquery-ui@1.10.5 node_modules/jquery-ui
webpack@1.12.14 node_modules/webpack
├── interpret@0.6.6
├── tapable@0.1.10
├── async@1.5.2
├── clone@1.0.2
├── esprima@2.7.2
├── supports-color@3.1.2 (has-flag@1.0.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── enhanced-resolve@0.9.1 (graceful-fs@4.1.3, memory-fs@0.2.0)
├── memory-fs@0.3.0 (errno@0.1.4, readable-stream@2.0.6)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── webpack-core@0.6.8 (source-map@0.4.4, source-list-map@0.1.6)
├── loader-utils@0.2.13 (big.js@3.1.3, json5@0.4.0)
├── uglify-js@2.6.2 (async@0.2.10, uglify-to-browserify@1.0.2, source-map@0.5.3, yargs@3.10.0)
├── watchpack@0.2.9 (graceful-fs@4.1.3, async@0.9.2, chokidar@1.4.3)
└── node-libs-browser@0.5.3 (string_decoder@0.10.31, https-browserify@0.0.0, tty-browserify@0.0.0, constants-browserify@0.0.1, path-browserify@0.0.0, punycode@1.4.1, os-browserify@0.1.2, process@0.11.2, assert@1.3.0, domain-browser@1.1.7, querystring-es3@0.2.1, timers-browserify@1.4.2, stream-browserify@1.0.0, events@1.1.0, util@0.10.3, readable-stream@1.1.13, vm-browserify@0.0.4, url@0.10.3, console-browserify@1.1.0, http-browserify@1.7.0, buffer@3.6.0, browserify-zlib@0.1.4, crypto-browserify@3.2.8)
webpack-dev-middleware@1.6.1 node_modules/webpack-dev-middleware
├── range-parser@1.0.3
├── mime@1.3.4
└── memory-fs@0.3.0 (errno@0.1.4, readable-stream@2.0.6)
flux@2.1.1 node_modules/flux
├── immutable@3.7.6
├── fbjs@0.1.0-alpha.7 (whatwg-fetch@0.9.0, promise@7.1.1, core-js@1.2.6)
└── fbemitter@2.0.2 (fbjs@0.7.2)
react@0.14.8 node_modules/react
├── envify@3.4.0 (through@2.3.8, jstransform@10.1.0)
└── fbjs@0.6.1 (whatwg-fetch@0.9.0, ua-parser-js@0.7.10, loose-envify@1.1.0, promise@7.1.1, core-js@1.2.6)
react-bootstrap@0.28.5 node_modules/react-bootstrap
├── uncontrollable@3.2.3
├── classnames@2.2.3
├── react-prop-types@0.3.0
├── keycode@2.1.1
├── invariant@2.2.1 (loose-envify@1.1.0)
├── warning@2.1.0 (loose-envify@1.1.0)
├── dom-helpers@2.4.0
├── react-overlays@0.6.2 (react-prop-types@0.2.2)
├── lodash-compat@3.10.2
└── babel-runtime@5.8.38 (core-js@1.2.6)
0.68s$ npm run-script build
> js16seminar@0.0.1 build /home/travis/build/Rostlab/JS16_ProjectF
> NODE_ENV=production node_modules/.bin/webpack --config ./webpack.production.config.js --bail --progress
module.js:327
    throw err;
    ^
Error: Cannot find module 'html-webpack-plugin'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/Rostlab/JS16_ProjectF/webpack.production.config.js:4:25)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.4.1/bin/node" "/home/travis/.nvm/versions/node/v4.4.1/bin/npm" "run-script" "build"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! js16seminar@0.0.1 build: `NODE_ENV=production node_modules/.bin/webpack --config ./webpack.production.config.js --bail --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the js16seminar@0.0.1 build script 'NODE_ENV=production node_modules/.bin/webpack --config ./webpack.production.config.js --bail --progress'.
npm ERR! This is most likely a problem with the js16seminar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production node_modules/.bin/webpack --config ./webpack.production.config.js --bail --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js16seminar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls js16seminar
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/Rostlab/JS16_ProjectF/npm-debug.log
The command "npm run-script build" exited with 1.
cache.2
store build cache
0.00s
4.15schanges detected, packing new archive
uploading archive
Done. Your build exited with 1.
```

Please revise this errors :)

**Comment by sacdallago** [comment]
@TheZoker can you help out here too? I think changing from v0.x to something more recent actually makes totally sense

**Comment by TheZoker** [comment]
@sacdallago @cotsog Is the guy from travis, who tries to resolve the issue we have in #203, we currently try to find the issue, why travis is failing the build

**Comment by sacdallago** [comment]
So you take care of it?

**Comment by TheZoker** [comment]
@sacdallago Yes I will. 
@cotsog I tried to clear the cache, but I get this error on the cache page:
`There was an error while loading data.`
Can you help me with that?

**Comment by TheZoker** [comment]
@sacdallago Can you access the cache page? 
https://travis-ci.org/Rostlab/JS16_ProjectF -> More options -> Cache

**Comment by sacdallago** [comment]
screen shot 2016-04-05 at 1 16 23 pm

**Comment by sacdallago** [comment]
It actually happens with every repo I have on there @TheZoker

**Comment by TheZoker** [comment]
Ref: https://github.com/travis-ci/travis-ci/issues/5855

**Comment by TheZoker** [comment]
Ref: https://github.com/travis-ci/travis-ci/issues/5855

**Comment by yashha** [comment]
Can we close this?

**Comment by sacdallago** [comment]
I can now access the caches @TheZoker @cotsog

**Comment by TheZoker** [comment]
Yes hey fixed their cache issue and also our issue is fixed

**Pull request closed without merging**
