### PR TITLE
Remove all those ugly and unneeded fields from the pagination

### PR DESCRIPTION
**Pull request by mammuth**
screen shot 2016-03-20 at 23 57 04

VS.

screen shot 2016-03-20 at 23 58 36

1 or 2 @yashha @jorjo1 ?

### CODE REVIEW

**Comment by sacdallago** [comment]
2!!!!!

**Comment by jorjo1** [comment]
two! :dancer:

**Comment by gyachdav** [comment]
2!!!!

**Comment by sacdallago** [comment]
@jorjo1 I have the email in which you originally wrote 1 ! :D don't try to hide behind github's edit button now :D :D

**Comment by jorjo1** [comment]
@sacdallago I did this on my smartphone and this was a typo! :joy: :hatching_chick: :

**Pull request merged**
