### PR TITLE
Landingpages

### PR DESCRIPTION
**Pull request by yashha**
Changes:
- Finished jon snow
- Far but not finished with the other both

Important!!:
moved marked down to /config/markdown and added html files to static  folder
Keep that in mind when merging

Somebody needs to continue :)
#169

### CODE REVIEW

**Comment by mammuth** [comment]
Dafuq, there were no merge conflicts, when merging locally? :open_mouth: 
Suspicious....

**Comment by mammuth** [comment]
Btw, what do our content-markdown files have to do with configs, @yashha ? :confused:

**Comment by yashha** [comment]
Wait I resolve it
I moved the markdown files to a folder in the config

**Comment by yashha** [comment]
ok ^^

**Comment by mammuth** [comment]
> I moved the markdown files to a folder in the config

Yes. 
I don't get why this makes sense.

**Comment by yashha** [comment]
It would serve the md files, too
And I thought static are the folders called which are served staticly

**Comment by yashha** [comment]
you broke it :(

**Comment by mammuth** [comment]
screen shot 2016-04-11 at 22 18 19
Seems like images in the markdown files have the wrong references.

**Comment by yashha** [comment]
They have been right

**Comment by yashha** [comment]
let me resolve it

**Comment by mammuth** [comment]
Decide what you want :stuck_out_tongue_winking_eye: 
For me the build is running fine when correcting the image references in the plod-description.md to /images/xy.png

**Comment by yashha** [comment]
Do you wanna have a different folder structure?

**Comment by mammuth** [comment]
Nah, let's leave it like this.

Build is fixed, so I merge now

**Pull request merged**
