### PR TITLE
blog start page text in front page

### PR DESCRIPTION
**Pull request by gyachdav**
- changed design
- added images
- hardcoded links to landing pages

@mammuth. needs design for HR tag in case there is currently no defined style

### CODE REVIEW

**Comment by yashha** [comment]
image

**Comment by goldbergtatyana** [comment]
Wow very nice!

**Comment by mammuth** [comment]
Cool! :+1:

**Comment by sacdallago** [comment]
Delete branch? Btw can someone clean up branches pls?

**Pull request merged**
