### PR TITLE
updated heroku key, after i reseted it because of issue #52

### PR DESCRIPTION
**Pull request by yashha**

### CODE REVIEW

**Comment by jorjo1** [comment]
What is exactly the difference between the old and new heroku keys?

**Comment by yashha** [comment]
Nothing, i have only reset it, so heroku gave me a new one and I have to update it here.

**Comment by sacdallago** [comment]
:D Yeah sorry, this was my fault :D :D

Btw guys: what we see on heroku is the latest version, right? Because I still see a lot of empty :P I see you are woking and PR a lot but I don't quite get why the page still looks like that

**Comment by yashha** [comment]
No problem :D
I thought you were right! ;)

It's not the newest version, but the newest version has still some bugs
I hope we can update our deploy today

**Comment by sacdallago** [comment]
Am looking forward to that :)

**Pull request merged**
