### PR TITLE
Fix #302

### LINKED ISSUE #302: jQuery and X-UA-Compatible tag missing on main page
I just validated the page with bootlint:
http://www.bootlint.com/?url=https:%2F%2Fgot-stats.herokuapp.com%2F

Issues:
- [ ] https://github.com/twbs/bootlint/wiki/W005
- [ ] https://github.com/twbs/bootlint/wiki/W002

### PR DESCRIPTION
**Pull request by TheZoker**

### CODE REVIEW

**Comment by mammuth** [comment]
So... I don't think, this PR does make sense.
Bootstrap isn't used in this project as it's imported here. We're using react-bootstrap.

(Also I don't quite get why you changed the jquery import to the css file of jquery...)

**Comment by mammuth** [comment]
However, let's see what @jorjo1 says :blush: maybe I oversaw something when I answered that quickly.

**Comment by TheZoker** [comment]
@mammuth What is the purpose of importing it there?

**Comment by jorjo1** [comment]
You'd better leave it as it was

> import 'jquery';
> import 'bootstrap/dist/css/bootstrap.css';
> import 'bootstrap/dist/js/bootstrap.js';

There is some black magic that webpack and react use and we don't mess with the file paths :dancer:

**Comment by TheZoker** [comment]
@jorjo1 But what is the purpose of those line, if you don't use jquery or these bootstrap files?

**Comment by jorjo1** [comment]
We _use_ jquery, but we use _webpack_ and _jquery_ as an external library for it. That's why we had to include it. 
That's a black magic for me, and it works now this way. :D @yashha set this up, he knows best why.

**Comment by yashha** [comment]
Would it be important to change it?
If it works after the change, you can change it :)
It doesn't matte if it is already minified or not, in the end it will be minified, because we are using webpack

**Pull request closed without merging**
