### PR TITLE
Character sorting and plod

### PR DESCRIPTION
**Pull request by mina-kleid**

### CODE REVIEW

**Comment by yashha** [comment]
It seems when loading
http://localhost:8080/characters/Cersei%20Lannister
it loads the plod with this 
https://api.got.show/api/plod/bySlug/Larys_Strong
Edit: also no image is getting displayed

**Comment by sacdallago** [comment]
? I get redirected to the docs?

**Comment by yashha** [comment]
True ^^

**Comment by sacdallago** [comment]
It's not us being tired, it's a recent change that should not be there https://github.com/Rostlab/JS16_ProjectA/commit/07cb218d6336f0c3672a2019fb61d03acf249f50

**Comment by sacdallago** [comment]
I've obviously asked for it to be put back.. let's see how many years we have to wait this time :clock1:

**Comment by mina-kleid** [comment]
Sorry there was a missing commit i didnt push, but seems that Project A changed somethiing

**Comment by sacdallago** [comment]
@togiberlin fixed quickly :+1:

**Comment by yashha** [comment]
It looks like its working now :)

**Pull request merged**
