### PR TITLE
Maybe fix of http warnings related to map

### PR DESCRIPTION
**Pull request by yashha**
Maybe a fix for #413

### CODE REVIEW

**Comment by jorjo1** [comment]
It works! I like it. Are you adding something else? I will merge in case of a 'no'. :}

**Comment by yashha** [comment]
No nothing to add. :)

**Comment by yashha** [comment]
Maybe update next time in tomorrow morning, just to be sure ;)
Currently we have a high click rate.

image

**Comment by sacdallago** [comment]
Currently? :D That number is basically fixed like that since this morning!

**Pull request merged**
