### PR TITLE
Added tum bar at top 2.0

### PR DESCRIPTION
**Pull request by yashha**
Well, hm
image

### CODE REVIEW

**Comment by sacdallago** [comment]
Very nice @yashha 
Last thing I would like to try out is: use the dark color-scheme, similar to the one I put on the [comment](https://github.com/Rostlab/JS16_ProjectF/issues/482#issuecomment-213373338) using the colors of the [corporate design](https://portal.mytum.de/pressestelle/tum_mit/2007nr2/09.pdf)

Maybe also @jorjo1 and/or @mammuth can help?

Again: thank you! This looks exactly like they want to have it.

**Comment by goldbergtatyana** [comment]
All, since we're working on the front page, can we please have the rostlab logo centered in the footer? Thanks!

**Comment by jorjo1** [comment]
@sacdallago @goldbergtatyana Should TUM logo be this big?

**Comment by gyachdav** [comment]
No merging until I say so. This issue is now on hold until further notice.

**Comment by yashha** [comment]
I think the map page has to be adjusted, before merge.

**Comment by mammuth** [comment]
Not only the map. You need to higher the main containers padding with the
height of the new tum-bar.

**Comment by sacdallago** [comment]
Me @gyachdav and @goldbergtatyana just talked and again the idea is:


You can go on working, this is not on hold anymore :P

The above are **official** colors for both background and text, which can be found here https://portal.mytum.de/pressestelle/tum_mit/2007nr2/09.pdf on the third page, the third set of colors on the right.

You can find all the logos and specification of the corporate design here:
https://portal.mytum.de/corporatedesign/index_html by accessing with your TUM credentials

Apart from that, please work on the other fixes that @mammuth and @yashha talked about.

@jorjo1 The size is "imposed" by the logo and corporate design. I know this is annoying as fuck but again: better do it right then having them tell us to re-do it for the fourth time now.

Please, like you always do, send us screenshots when you have something to show and **thank you** again :)

**Comment by sacdallago** [comment]
Hi guys,
anything on this regard? We got another email from the legal office asking if we "accepted their conditions" :P :P

**Comment by gyachdav** [comment]
Rephrasing what @sacdallago just said - we need this done ASAP. Should be up live within the hour. Whoever is I front of a laptop please take care now.   

This coming from the president of the university!

**Comment by yashha** [comment]
I don't have access to any of the guidlines on https://portal.mytum.de/corporatedesign/index_html.
Are they important?

@sacdallago 
Do you want this on the top of the page?
https://cloud.githubusercontent.com/assets/6240943/14739285/e3c168da-0886-11e6-8a10-7e4f63884d92.jpg

**Comment by sacdallago** [comment]
Yes please @yashha I can give you the pngs and color for the background, hold on

**Comment by yashha** [comment]
Why not the svgs, I am currently using?

**Comment by sacdallago** [comment]
Official white TUM logo:
tum_logo_weiss_rgb_p

It's white... :D so you probably won't see it here :D :D :D :D just click on it, open it, and download it

**Comment by sacdallago** [comment]
Color scheme:
1. 353535 --> https://www.colorcodehex.com/353535/
2. 828282 --> https://www.colorcodehex.com/828282/
3. cecece --> https://www.colorcodehex.com/cecece/

~~I would say 353535 for background! You should use the same background color for the rest of the page (I have tried to inspect the page and change the `body {    background: #1f1f1f; ..}` to `body {    background: #353535; ..}` and you can barely see the difference!~~

**Edit**: It looks terrible on the rankings page. Just keep the two different backgrounds and send us a screenshot please.. Should not look that bad

Thanks

**Comment by yashha** [comment]
Its a bit brighter than before:
image

**Comment by sacdallago** [comment]
Good @yashha we are almost there. How about keeping the `body` color the same? Screenshot of that please?

**Comment by yashha** [comment]
image
Is there no darker color provided by tum?

**Comment by sacdallago** [comment]
Unfortunately not 😢 

I would keep this last one, @gyachdav I need your ok and @goldbergtatyana as well

**Comment by gyachdav** [comment]
Green light to merge from me and I okay for @goldbergtatyana too

dont wait with the merge please.

**Comment by sacdallago** [comment]
Ok than please @yashha commit your last work and I will close this :)

Thank you soso much

**Comment by yashha** [comment]
Now I still have to fix some spacings, because of the new bar at the top we have to adjust the spacings of many pages.

**Comment by sacdallago** [comment]
Ping me when it's time to review and merge :)

**Comment by yashha** [comment]
It's done. :)
@sacdallago I don't know, maybe @jorjo1 or @mammuth check if every spacing is fixed
Or we deploy it and fix it with an quickfix afterwards

**Comment by gyachdav** [comment]
In merging. Chris deploy ASAP. 

All please go over and prepare hotfixes. We need this done ASAP.

**Comment by gyachdav** [comment]
@yashha put in the following changes:

TUMLogoWritten{ margin-top:: 50px;}
TUMLogo{  remove margin-top or margin-top:0px;}

please modify asap.

**Comment by yashha** [comment]
So a smaller bar? @gyachdav 
image

**Comment by gyachdav** [comment]
yes way way shorter. please check on mobile, i only checked with dev tools that this works on desktops

**Comment by yashha** [comment]
image
s5:
image

**Comment by yashha** [comment]
shell I make it short like on mobile on desktop too?

**Comment by gyachdav** [comment]
Yes

**Pull request merged**
