### PR TITLE
fix for character names block on map

### PR DESCRIPTION
**Pull request by jorjo1**
#467

### CODE REVIEW

**Comment by jorjo1** [comment]
image
Much nicer representation with margins and paddings etc

It's merge-able

**Comment by yashha** [comment]
Its nice until width of about 411

**Comment by yashha** [comment]
image

**Comment by sacdallago** [comment]
Where's the donate bar on the screenshot?
I think this branch is not too much up-to date. Please first try to merge develop into here, see if nothing goes wrong and re-open the PR.

**Comment by yashha** [comment]
Ok navbar still buggy here

**Comment by yashha** [comment]
image
working fine again

**Comment by yashha** [comment]
image
working fine again

**Pull request merged**
