### PR TITLE
Phrasing about Twitter Sentiments on Ranking

### LINKED ISSUE #40: Make Ranking page
Details and main idea: 

Refers also to #59 
- [x] "Who dies next" Both most likely to die characters (1 vs. 1)
- [x] top 5/10 most likely to die next
- [x] top 5/10 loved characters
- [x] top 5/10 hated characters
- [x] top 5/10 survivors

### LINKED ISSUE #370: Tweet feature on rankings page
I love the feature, extremely good idea! Maybe:
1. change the default tweet from "I love XYZ" to "I hate XYZ" for the :-1: button
2. The link from www.got.show to got.show
3. Put the @asoiad for our twitter account

:D Who knows, maybe I _do_ love yellow dick... If got.show says so :cry: 

screen shot 2016-04-10 at 3 24 25 pm

### PR DESCRIPTION
**Pull request by mammuth**
screen shot 2016-04-10 at 14 36 45

@marcusnovotny, @gyachdav What do you say to this phrasing?

Closes #40 
Closes #370

### CODE REVIEW

**Comment by marcusnovotny** [comment]
I think it's good. Thanks for the quick action! Only other suggestion I could make is that we add a bunch of feelings we measure in a second line, like:

Most positive mentions:
(love, joy, enthusiasm)

Most negative mentions:
(hate, fear, anger, frustration) 

So people get an idea why popular characters end up on the negative mentions side. I'm afraid it might look really cramped though plus the list is not exhaustive at all. That can seem disturbing.

Giving @gyachdav the last call here. Otherwise merge, let's not overcomplicate things!

**Comment by gyachdav** [comment]
Phrasing LGTM. 

Have a question mark next to the heading and a popup giving the feelings @sacdallago wanted to have in the sub heading.  

Good work!

**Comment by sacdallago** [comment]
Maybe integrate this before merging? https://github.com/Rostlab/JS16_ProjectF/issues/370

**Comment by mammuth** [comment]
screen shot 2016-04-10 at 17 05 14

Now with tooltip on hover. :+1:

**Comment by mammuth** [comment]
screen shot 2016-04-10 at 17 14 22
Changed twitter-hate message and added our account.

**Comment by gyachdav** [comment]
Cool!

**Pull request merged**
