### PR TITLE
Fixed showing plods on detail page

### LINKED ISSUE #316: Euron Greyjoy has 2 different PLOD's on the website
https://got-stats.herokuapp.com/characters/Euron%20Greyjoy 
PLOD 0.932%

On the start page PLOD: 94.2%

p.s. 
love the new release to staging!

### PR DESCRIPTION
**Pull request by yashha**
image
image
By the way the design bug in the second image should be fixed at some point

Closes #316

### CODE REVIEW

**Comment by yashha** [comment]
image
I think the details still have to be redesigned at some point ;)

**Comment by yashha** [comment]
maybe something like this?
image

**Comment by gyachdav** [comment]
Couple of nice to have suggestions:

Titles put in bullet points. Group and three bullets in columns. 

For books: each boo has a cover image that can be easily found. How about instead of using book names using the image covers instead. Image covers can be reduced to small icon size and can appear circular.

**Comment by jorjo1** [comment]
Yes, I will do this too :}
We still have to fix a big part of the page.

**Comment by yashha** [comment]
#358

**Comment by sacdallago** [comment]
OK. My take is: merge this (if the code is functional and the feature, although needs polishing, is there) and go on working on fixes later.

**Comment by yashha** [comment]
I can't merge it because i made the request :P

**Comment by sacdallago** [comment]
I know! :) @mammuth @jorjo1 ?

**Pull request merged**
