### PR TITLE
restructure footer

### PR DESCRIPTION
**Pull request by Andrew094**

### CODE REVIEW

**Comment by mammuth** [comment]
Cool! :+1:

**Comment by jorjo1** [comment]
Hi @Andrew094 , we just have to remove
`footer { height: 250px; }`
because otherwise the elements are in conflict on smaller screen size (footer and copyright).

I think though that we should reconsider which license we're putting there, if any. I think this field is not necessary - we can simply link the "License" in the footer :sunglasses:

**Comment by sacdallago** [comment]
Sorry to bother again with the footer.
I just issued RBG for an SSL certificate and they say that to get it it's **preferred** we show the affiliation with TUM or Rostlab across the webpage. The TUM link is fine, but putting a logo wouldn't hurt either.
Could you please put either the TUM or RostLab logo in the footer? Not like the 500x500 version of it, just that _it's there_

Merci

**Comment by jorjo1** [comment]
Logo we put. Happy we are. :+1: 

@sacdallago where do we find Rostlab assets?

**Comment by mammuth** [comment]
screen shot 2016-03-21 at 15 44 18

Like this?

Btw, @Andrew094 what's the solution where to store static stuff like images, so it can be referenced relatively (like /static/images/tum_logo.jpg) ?

**Comment by sacdallago** [comment]
Looks nice!

**Comment by sacdallago** [comment]
Again. I am so sorry. I hate myself for doing this:

Maybe the footer is the best place to put a direct link "_feedback_" that goes to the github issues of your repo. **Maybe**. Maybe it's better to put it somewhere else. But having a feedback button or link would be very nice :)

**EDIT**: Or if you want to set up a mailing thing with a form and a _contact us_ :D either way

**Comment by jorjo1** [comment]
done. #112

**Comment by gyachdav** [comment]
Thanks. Please merge.

**Pull request merged**
