### PR TITLE
Episode recap

### PR DESCRIPTION
**Pull request by gyachdav**
https://github.com/Rostlab/JS16_ProjectF/issues/500

Edit by Yasar:
TODO after merge:
FB post: check this out, seasons 6 episode 1 is behind us and we can report that our algorithm was spot on! Read about it in our episode recap [link].

Twitter post: check this out, seasons 6 episode 1 is behind us and we can report that our algorithm was spot on! Read about it in our episode recap [link to this blog entry].

### CODE REVIEW

**Comment by yashha** [comment]
We still have to make a link from the start page to it? don't we?

**Comment by gyachdav** [comment]
Im working on it but Travis fails again with the a similar error to what you got earlier @yashha. 

can you tell me how to fix?

**Comment by yashha** [comment]
There was a cache problem I think now it is kind of working isn't it?
Edit: same error?

**Comment by gyachdav** [comment]
yup, it magically fixed itself

**Comment by gyachdav** [comment]
please merge

**Comment by yashha** [comment]
@sacdallago ?

**Comment by gyachdav** [comment]
@yashha you can merge if all good. 

@sacdallago please deploy

**Comment by sacdallago** [comment]
@yashha careful you were working on a branch and then PR that branch into this other feature branch. If I wouldn't have noticed this, there might be some lost changes! (as I delete branches after merging)

**Pull request merged**
