### PR TITLE
Added antagonists component, sentiments & PLODs are missing

### PR DESCRIPTION
**Pull request by yashha**
Related #177
Related #235

### CODE REVIEW

**Comment by mammuth** [comment]
ToDo:
- [x] Map with both characters on it (@mammuth)
- [x] Sentiments (@yasha) (moved to #256)

**Comment by gyachdav** [comment]
Very nice!

We should clean out the dead characters from the who will be eliminated next face offs. it makes little sense to keep it like that. 

Is there a file I can edit the list of the facedoff characters?

**Comment by goldbergtatyana** [comment]
@gyachdav I think this is the one you're looking for http://pastebin.com/Qs9PCJYH

**Comment by mammuth** [comment]
You can edit this file:
https://github.com/Rostlab/JS16_ProjectF/blob/develop/app/components/common/AntagonistsComp/antagonists.json

**Comment by gyachdav** [comment]
Thanks

**Comment by goldbergtatyana** [comment]
The images of Brandon Stark, Jaime Lannister and Ramsay Snow do not fit the height of the frame of the antagonists component. There is space between the picture and the bottom side of the frame.

**Comment by gyachdav** [comment]
As discussed [here](https://docs.google.com/document/d/1TxGVoVNiqhclnwG5pw8-iRYljKpmjEn91FyTw51IyWk/edit#bookmark=id.mwhcx96ncuxo) we will generate a new heading for each loaded pair of antagonists. 

The heading will be changing on each load:
1. randomly use one of the template headings (list of template headings below)
2. randomly pick antagonists
3. plug into the heading either character_with_higher_plod, character_with_lower_plod or both depending on the template

Templates for heading (will be shown in a random order upon every page load)
- character_with_higher_plod is likelier to die than character_with_lower_plod 
- character_with_higher_plod is likelier to get whacked
- character_with_higher_plod will surely be the first to be slain
- The future of character_with_higher_plod is blood and fire
- character_with_higher_plod will bite the dust
- character_with_lower_plod would outlive character_with_higher_plod

**Comment by gyachdav** [comment]
I would also like to edit the list of template headings, where can I find those?

**Comment by yashha** [comment]
Here: :)
https://github.com/Rostlab/JS16_ProjectF/blob/develop/app/components/common/AntagonistsComp/AntagonistsComp.jsx#L70

**Pull request merged**
