### PR TITLE
New structure for Ranking page

### PR DESCRIPTION
**Pull request by jorjo1**
It's not a 100% ready but you can take a look and share your opinion

Waiting for #336 @yashha ! :)

### CODE REVIEW

**Comment by yashha** [comment]
@jorjo1 If you merge it you can use it :)

**Comment by yashha** [comment]
I like the design, maybe a bit transparent red when hovering over the list items
And all list should look similar at some point :)

**Comment by jorjo1** [comment]
@yashha Thanks for the tip :) I am still working on it, so don't merge ^^

**Comment by mammuth** [comment]
screen shot 2016-04-09 at 19 32 40
There is pretty much space to the right of the names. Are you planning to fill it somehow?

Otherwise, it looks cool!

**Comment by yashha** [comment]
We could do a max-width and center it :)

**Comment by gyachdav** [comment]
Small character images next to name a la map search bar?

**Comment by jorjo1** [comment]
I am working on the idea of integrating small images next to the characters.

**Comment by sacdallago** [comment]
Open too long!

Merge and go on working after that, if this PR is ok

**Pull request merged**
