### PR TITLE
Got sentiments working on startpage! :)

### LINKED ISSUE #256: Add sentiments to homepage
Part of #177

### PR DESCRIPTION
**Pull request by yashha**
Closes #256
Edit: Also 
- added Bronn to the images folder, because he was missing
- updated serverside to new example app of d4

### CODE REVIEW

**Comment by mammuth** [comment]
Closes #256 

Edit, I guess this needs to be in the PR desciption, to make Github closing the issue automatically. -> Edited your comment.

**Comment by yashha** [comment]
Can I merge? :)
Edit: I want to try sqash and merge :D

**Comment by mammuth** [comment]
I am on mobile right now, so can't review your changes properly, sry.

**Comment by yashha** [comment]
image

**Comment by yashha** [comment]
There is still a bug that the background lines of the charts are moving on both charts.
Edit: when scrolling.

**Comment by mammuth** [comment]
Hm. Some thoughts:
- There needs to be a heading / description / legend what the graphs are showing
- Nobody will notice that little plod value next to those cool graphs. Even if we name it properly like "is likelihood of death is XY%"
- If we don't have tweets before March we should adjust the graphs resolution so it doesn't look that empty

**Comment by yashha** [comment]
Sounds valid, I'll look into it.
Legend shows when you click on the about button.
@CavidSalahov 
Do you know in which ways we can adapt the chart?

**Comment by yashha** [comment]
@julienschmidt 
Can have you ideas how to solve that?
I already found the startDate parameter :)

> @mammuth 
> If we don't have tweets before March we should adjust the graphs resolution so it doesn't look that empty

**Comment by julienschmidt** [comment]
@marcusnovotny is responsible for the visualization part

I'm not aware of any `startDate` parameter in our project. That might be D5.

**Comment by marcusnovotny** [comment]
We're working on a fix for the missing tweets. Showing only the last two weeks basically renders the graph useless.

You can manually adjust the shown date range on startup with the optional startDate parameter you found already, e.g.

`var chart = new characterChart(d3.select("#chart"), "/csv/{{slug}}.csv", new Date(2016,02,01));`

Default shown date range for now is 1.1.2014 - today. If you want I can automatically add that the graph adjusts to the available data if it's less than a few months. I'd much rather get the tweets though :grimacing: 

Please report our visualization bugs over at the D4 repo
https://github.com/Rostlab/JS16_ProjectD_Group4/issues

You're using an older implementation too, you should get the one @sacdallago is using over at http://csv.got.show/

**Comment by yashha** [comment]
> If you want I can automatically add that the graph adjusts to the available data if it's less than a few months.  

That would be awesome :)

**Comment by marcusnovotny** [comment]
I'll keep you updated, most likely getting it done tomorrow

**Comment by marcusnovotny** [comment]
& How can I run that test site? Hard for me to debug if I can't experience it myself :)

**Comment by yashha** [comment]
image

Any ideas how to design further?

**Comment by goldbergtatyana** [comment]
very very cool! we need a label on the y axis telling what positive and what negative values represent. Love. Hate.

**Pull request merged**
