### PR TITLE
Fixed issue that charts has been loaded twice 

### PR DESCRIPTION
**Pull request by sacdallago**
Revert, reverted original PR #430 in favor of further testing before deployment and merge with develop.

The fast way of testing this is someone coming to rostlab tomorrow with this version running somewhere locally, the long way is me setting up a testing server.

### CODE REVIEW

**Comment by yashha** [comment]
Chrome:
image
image

**Comment by yashha** [comment]
That was not a big change

**Comment by yashha** [comment]
I can run a test heroku if you want.
Edit: Maybe just @mammuth @jorjo1 start it and check it?

**Comment by yashha** [comment]
It is only a fix for #369

**Comment by sacdallago** [comment]
Yes please, try to deploy back on heroku! I'll try it out tomorrow with a couple macs, see if it solves the other problem as well (I really believe it should)

**Comment by yashha** [comment]
You don't use our staging branch, do you?

**Comment by sacdallago** [comment]
Nope I use develop!

**Comment by yashha** [comment]
Wait I can't really use it too.
Because it would have to merge first into develop, I'll make a new branch.

**Comment by yashha** [comment]
So now lets wait until there shows something on the charts :D
I deployed.
https://got-stats.herokuapp.com/
Edit: and it works

**Comment by sacdallago** [comment]
Will test it out in an hour! Thank you!

**Comment by sacdallago** [comment]
Fantastic. This indeed seems to solve also #396

**Comment by marcusnovotny** [comment]
Guys, great job. I keep coming back to got.show and the site looks a little more amazing every day. Thanks for your loyal service! :grin:

**Pull request merged**
