### PR TITLE
Added chart to detail page :)

### LINKED ISSUE #265: Integrate d4 chart into characters page

### PR DESCRIPTION
**Pull request by yashha**
closes #265 
#275

### CODE REVIEW

**Comment by mammuth** [comment]
I'm busy all day long and without my personal laptop. 

I can review your changes in the evening. If you want to see this merged sooner, someone else should do it :wink:

**Comment by sacdallago** [comment]
@jorjo1 please have a look at the code and merge if it's OK.

Thx

**Comment by mammuth** [comment]
screen shot 2016-04-07 at 13 18 23

Can't take a deeper look into it due to the twitter issues, mentioned in some other issues.

**Comment by yashha** [comment]
It is not even working locally for me .. I have to look over it again

**Comment by mammuth** [comment]
Isn't it intended that the graph is replacing the tabs with dummy data?
screen shot 2016-04-07 at 17 58 41

**Comment by goldbergtatyana** [comment]
No dummy data, please!

**Comment by mammuth** [comment]
I don't think I get your comment right, but since it seems to be a response to my comment, I'm going to rephrase it:
_**Isn't it intended that the graph is replacing the tabs?**_

**Comment by gyachdav** [comment]
Yes @mammuth is correct. the  graph is replacing the tabs. 

(on a separate note then, where is the data from D5 come in? only in the ranking page)

**Comment by sacdallago** [comment]
Yes that was the Ida. But after the graph there should still be this part we discusse about of numero of positive/negative/controversial tweets that you get from the Group ≠ than the one that gives you the graph

**Pull request merged**
