### PR TITLE
Edit static content through markdown files. Added start, about and fo…

### PR DESCRIPTION
**Pull request by Andrew094**
…oter.

### CODE REVIEW

**Comment by sacdallago** [comment]
Can something else possibly fail?

**Comment by sacdallago** [comment]
Also... Seriously... One week and that's all the static text you came up with? :D Even through [the monkey theorem](https://en.wikipedia.org/wiki/Infinite_monkey_theorem) we would by now have more reasonable text to present :D :D :D

**Comment by Andrew094** [comment]
It is not about the text which will be changed later anyways, it is a solution to include the text through markdown files. I also looked at https://github.com/MoOx/statinamic but found it difficult to even get it running, so I switched to react markdown which I think is sufficient for the amount of static content on the page.

**Comment by mammuth** [comment]
I like your solution, @Andrew094. It looks clean.

What's the idea on how to edit for example two placeholders on one page? For example the intro text and the text at the bottom below "For Developers" on the about-page. Are we creating multiple files in parent-folders like:
_static/about/intro.md
static/about/developer.md_

**Comment by Andrew094** [comment]
yes, that could be done,
you then would have to include both md files in your jsx component.

**Comment by sacdallago** [comment]
Yeah, yeah.. The idea looks good but I have to admit I was waiting for something a bit less "_text which will be changed later anyways_".
That we are gonna edit it long doesn't mean that you don't have to put some effort into writing it :D still your job

And please ask @Emiliyana or whoever from E is responsible for this project to take care of having a clean PR **before** merging it

**Pull request merged**
