### PR TITLE
Updated css like in #391 discussed

### PR DESCRIPTION
**Pull request by yashha**

### CODE REVIEW

**Comment by mammuth** [comment]
Formulas look good. 
Looks like nothing is broken by this.

When looking at 17px font-size I start feeling like being 30 years older. But I guess you guys did some thoughts on that, so let's merge it.

**Comment by sacdallago** [comment]
@mammuth I feel like 30 y/o

**Comment by mammuth** [comment]
You seem to missed the **_older_** :wink:

**Comment by sacdallago** [comment]
No, I didn't. I feel like I'm 30 y/o.
Both mentally and physically.. visually: meh... visionally: absolutely.

**Pull request merged**
